# Site settings
title: b0-a
email:
description: Ma webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://b0-a.github.io" # the base hostname & protocol for your site

# Identity
your-name: b0-a
your-title: Da Malware Analyst

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: 
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
